# Generated by Django 3.2.5 on 2022-05-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='blog')),
                ('title', models.CharField(max_length=1000)),
                ('slug', models.SlugField(blank=True, max_length=1000, null=True)),
                ('category', models.CharField(choices=[('P', 'PROGRAMING'), ('PR', 'PROJECT'), ('GM', 'GAME')], max_length=2)),
                ('sub_category', models.CharField(choices=[('C', 'C'), ('CPP', 'CPP'), ('JV', 'JAVA'), ('PY', 'PYTHON'), ('FL', 'FLUTTER'), ('GME', 'GAME')], max_length=3)),
                ('content1', models.TextField(blank=True, null=True)),
                ('contentcode1', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(upload_to='blog')),
                ('content2', models.TextField(blank=True, null=True)),
                ('contentcode2', models.TextField(blank=True, null=True)),
                ('image2', models.ImageField(upload_to='blog')),
                ('content3', models.TextField(blank=True, null=True)),
                ('contentcode3', models.TextField(blank=True, null=True)),
                ('image3', models.ImageField(upload_to='blog')),
                ('contentkesimpulan', models.TextField(blank=True, null=True)),
                ('link1', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('link2', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('link3', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('contentvidio', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload_to', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='blog')),
                ('title', models.CharField(max_length=1000)),
                ('slug', models.SlugField(blank=True, max_length=1000, null=True)),
                ('category', models.CharField(choices=[('P', 'PROGRAMING'), ('PR', 'PROJECT'), ('GM', 'GAME')], max_length=2)),
                ('sub_category', models.CharField(choices=[('C', 'C'), ('CPP', 'CPP'), ('JV', 'JAVA'), ('PY', 'PYTHON'), ('FL', 'FLUTTER'), ('GME', 'GAME')], max_length=3)),
                ('content1', models.TextField(blank=True, null=True)),
                ('contentcode1', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(upload_to='blog')),
                ('content2', models.TextField(blank=True, null=True)),
                ('contentcode2', models.TextField(blank=True, null=True)),
                ('image2', models.ImageField(upload_to='blog')),
                ('content3', models.TextField(blank=True, null=True)),
                ('contentcode3', models.TextField(blank=True, null=True)),
                ('image3', models.ImageField(upload_to='blog')),
                ('contentkesimpulan', models.TextField(blank=True, null=True)),
                ('link1', models.CharField(default='', max_length=1000)),
                ('link2', models.CharField(max_length=1000)),
                ('link3', models.CharField(max_length=1000)),
                ('created_by', models.CharField(max_length=1000)),
                ('contentvidio', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload_to', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
